### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by p-linnane** [gvanas/blahtexml#11]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. We are [considering deprecating blahtexml](https://github.com/Homebrew/homebrew-core/pull/125704) due to the lack of a new release for a number of years. I've noticed recent commits, so wanted to clarify the status of the project. Can we expect new releases?

**Comment by gvanas** [comment]
Hello, thanks for the heads up. Indeed I haven't been actively working on blahtexml for a few years, as it works fine for me as is (I use it almost every day as part of our documentation flow).

There were a couple of (minor) bug fixes recently, and I'd be happy to make a release with these. This said, I guess the decision of keeping or not blahtexml in Homebrew would be best based on how many other people find it useful.

**Comment by p-linnane** [comment]
We are happy to keep packaging blahtexml. We review software that has not had a new release for an extended period of time to make sure it is still maintained. If you're willing to cut a release I am happy to close the deprecation PR and package the new release. Thanks!

**Comment by gvanas** [comment]
I just made a release and tagged it [version 1.0](https://github.com/gvanas/blahtexml/releases/tag/v1.0)!

**Comment by p-linnane** [comment]
Thank you! I've opened https://github.com/Homebrew/homebrew-core/pull/126830 to package this new release in Homebrew.
