### ISSUE TITLE
Does not compile with GCC 4.7

### ISSUE THREAD

**Issue by papile** [gvanas/blahtexml#5]
Hello,
  Not sure if this is being maintained here anymore, but unistd.h is not imported by default anymore in gcc 4.7. I notice the 2 files this import is needed there is a guard clause for if this is being compiled for OS X. Removing those guard clauses allows it to compile normally.

**Comment by gvanas** [comment]
Thanks for the comment. I removed the guard clauses, it should now compile fine with GCC 4.7.
