### ISSUE TITLE
Found crashes with --mathml by fuzzing with afl++

### ISSUE THREAD

**Issue by sijanec** [gvanas/blahtexml#8]
Hello!

I've ran afl++ on commit 92f2c5ff1f2b00a541b2222facc51ec72e5f6559 (current master) and it has found the following inputs to crash the blahtex interpreter when passing --mathml as an argument.

`{{}{}}`, `((^{
    {}{}}`, `?i^?k^{{}{}}`, `{}{}`, `{}{}{}`, `\!\,`, `^{^{{}{}{}}}`.

To reproduce crashes: `echo "{}{}" | ./blahtex --mathml`

I've fuzzed on `Linux ass 5.10.0-18-686-pae #1 SMP Debian 5.10.140-1 (2022-09-02) i686 GNU/Linux` on Intel T2400 CPU. No other platforms have been tested.

I didn't test for the impact those crashes have on security or integrity. Apple pages documents containing such inputs show no visual indication of library crash as tested on iPad. As I do not have access to one, I cannot fully verify, nor do I know how this library is used by the software.

Tarball with afl++ output: http://upload.sijanec.eu./blahtex.tar.gz

**Comment by LdBeth** [comment]
this patch should fix the problem https://github.com/LdBeth/blahtexml/commit/d3173edfe3c6da2cd45081f3a92ce224805bc78d

The reason is when then zero width space is the only child of a `mrow` node, some thing wrong would happened.

**Comment by LdBeth** [comment]
Welp, I think it is a bad idea to generate a zero space for these cases since that affects the MathML output of normal equations, it is better just return an empty `mrow`.

**Comment by gvanas** [comment]
Thanks for the patch!

I see that the patch is on a branch that diverged from this master branch. I would be happy to merge your changes, but I am afraid that commit [daa648](https://github.com/LdBeth/blahtexml/commit/daa648cf9d1be47b76500820938cda617dbd1255) will break compatibility.

One option would be to cherry-pick the fix.

Any thoughts/preferences?

**Comment by LdBeth** [comment]
@gvanas I have formatted the PR #10 that only pickup relevant changes and is based on d47606e, so you can merge the fix.
